sudo: required

services:
  - docker

before_install:
  - docker --version
  - sudo docker build --rm=false -t jgm1986/rts2docker .
  - docker run -d -P --name=rts2docker jgm1986/rts2docker /bin/sh -c "echo 'RTS2 Docker image.';"

script:
  - docker ps
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "[ INFO ] Uploading Docker image to DockerHub.";
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    DOCKER_ID=$(sudo docker ps -aqf "name=rts2docker");
    sudo docker commit -a "Javier Gusano Martinez <jgm1986@hotmail.com>" -m "version latest" $DOCKER_ID jgm1986/rts2:latest;
    docker tag jgm1986/rts2:latest jgm1986/rts2:latest;
    sudo docker images;
    docker push jgm1986/rts2;
    echo [ INFO ] Done!;
    fi
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    DOCKER_ID=$(sudo docker ps -aqf "name=rts2docker");
    sudo docker commit -a "Javier Gusano Martinez <jgm1986@hotmail.com>" -m "version develop" $DOCKER_ID jgm1986/tests:develop;
    docker tag jgm1986/tests:develop jgm1986/tests:develop;
    sudo docker images;
    docker push jgm1986/tests;
    echo "Uploaded to DockerHub test site.";
