sudo: required

services:
  - docker

before_install:
- docker pull ubuntu:16.04
- docker run -d ubuntu/16.04 /bin/sh -c "echo 'Hello World from Ubuntu.';"

script:
- docker ps

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "[ INFO ] Uploading Docker image to DockerHub."
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jgm1986/rts2;
    fi
